import { buildPrompt } from '../src/prompt.ts';
import { loadConfig } from '../src/config.ts';
import { openDb } from '../src/db.ts';
import { getState, startSleep } from '../src/events.ts';
import { matchFast } from '../src/fastpath.ts';
const cfg = loadConfig({ ALICE_WEBHOOK_SECRET: '0'.repeat(32), TZ: 'Europe/Moscow', CHILD_NAME: 'Андрей', CHILD_BIRTHDATE: '2026-09-02', DB_PATH: ':memory:', WORKER_ENABLED: 'false' } as NodeJS.ProcessEnv, { cwd: process.cwd() });
const db = openDb({ path: ':memory:' });
const now = new Date('2026-09-15T11:02:00.000Z');
const size = (l: string, t: string) => console.log(l.padEnd(30), String(t.length).padStart(6), 'символов', String(t.split('\n').length).padStart(4), 'строк');
size('простая, 0 карточек', buildPrompt({ cfg, rawText: 'андрей заснул', fast: matchFast('андрей заснул'), fastEvent: null, state: getState(db, cfg, now), now }));
startSleep(db, cfg, { at: '2026-09-15T08:00:00.000Z' });
const st = getState(db, cfg, now);
size('канонический, 1 карточка', buildPrompt({ cfg, rawText: 'андрей заснул', fast: matchFast('андрей заснул'), fastEvent: null, state: st, now }));
const p = 'нет, он заснул в девять, а не в десять, он не спал до этого';
size('поправка, 3 карточки', buildPrompt({ cfg, rawText: p, fast: matchFast(p), fastEvent: null, state: st, now, recentEvents: [] }));
db.close();
